### ISSUE TITLE
Patch ief_clone_button-1590146-18-default-off to inline_entity_form failed under drupal-org.make

### ISSUE THREAD

**Issue by avinash-vllbh** [lter/deims#29]
ief_clone_button-1590146-18-default-off.patch couldn't be patched with inline_entity_form which results in build fail.

**Comment by davereid** [comment]
I know the Inline Entity Form module had some big commits to it recently. Probably the patch in https://drupal.org/node/1590146 needs to be re-rolled.

**Comment by rraub** [comment]
Hi Dave, I'm working with Avinash and we're both kind of new to drupal development so forgive the basic/fundamental questions I'm asking below.

Tying the deims build to the bleeding edge of an dependencies development branch seems like a too fragile of a setup. We were just getting our feet wet with builing deims via drush when some changes to inline_entity_form broke our build process. 

We were able to work around this problem by picking out a specific revision to checkout for inline_entity_form that worked with the patches. I am curious why this isn't common practice for all the dependences that are configured on their bleeding edge development branch?  

This would allow you to isolate the task of upgrading dependencies (and testing their integration); instead of trying to hit a moving target every time you go to build. I can see the advantage of this from a continuous integration standpoint, but it still seems like there are too many things can change each time we run drush when we want to test just our one modification.

**Comment by davereid** [comment]
I totally agree with you that we should definitely lock the version down to a more stable release. I don't think we can use a specific commit because _I think_ that Drupal.org will not package it in that case. It looks like we should start trying to target and test the 7.x-1.4 release.

**Comment by rraub** [comment]
Related commit by @isangil  https://github.com/lter/deims/commit/cb60120c1e479ea93cbbb39f7a7cf519c6d60120

**Comment by isangil** [comment]
This issue is solved by now with the 1.3 release and patch updates, as @rraub cites.  However, there is on-going work to include the patch in the module (see https://www.drupal.org/node/1590146 ) and related. Closing for now.
