### ISSUE TITLE
Chosen in contrib and custom?

### ISSUE THREAD

**Issue by isangil** [lter/deims#69]
I have to verify, but it would seem that the chosen folder that hosts the chosen module may appear both in "contrib" and "custom"....

**Comment by davereid** [comment]
I believe a while back we had a custom fork of the Chosen module in our custom directory. But we switched to using a patched version of the contrib module since most of the improvements we made were committed to the module. So it may be the old forked version in /custom should just be deleted on the implementing site?

**Comment by isangil** [comment]
On March you did commit that change (see 409a98671bf1eb2a69f4b87e0099ee44ac666db5), which effectively removed your chosen handy fork from the profiles/deims/modules/custom directory.

After trying to replicate this oddity, I do not find an instance of the chosen fork under /custom/ on a fresh download `drush dl deims`.

 Therefore I think it was doing something wrong.  Nothing further here, I'm closing this issue - thanks Dave @davereid
